import { Menu, Popover, Transition } from "@headlessui/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Fragment, useContext, useEffect, useState } from "react"
import toast from "react-hot-toast";
import NavItem from "../Components/NavItem";
import ThemeToggle from "../Components/ThemeToggle";
import iranIcon from '../public/images/ir.svg';
import EnglishIcon from '../public/images/gb.svg';
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import logo from '../public/images/logo2.png';
import { signOut, useSession } from "next-auth/react";
import AuthContext from "../Components/context/AuthContext";
import axios from "axios";
import Subdrop from "../Components/subdrop";

export default function Header({ children, title, height = 'h-full' }) {
    const { data: session, status } = useSession()
    const [menu, setmenu] = useState(1000);
    const [userdata, setuserdata] = useState([]);
    const [lng, setlng] = useState('')
    const [selectcategory, setselectcategory] = useState('همه دسته بندی ها')
    const togglemenu = () => {
        menu === 0 ? setmenu(1000) : setmenu(0);
    };

    const logout = () => {
        toast.loading('از حساب خود خارج شدید');
        localStorage.clear();
        window.location.href = '/';
    }
    const router = useRouter();
    const togglenav = (link) => {
        router.push(link);
        togglemenu();
    }

    useEffect(() => {
        setlng(localStorage.getItem('lng'))
    }, [setlng])
    useEffect(() => {
        setuserdata(JSON.parse(localStorage.getItem('datauser')));
    }, [])





    return (
        <div className={`w-full bg-gray-100 lg:pb-0 ${height}`}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-full z-50 fixed top-0 right-0 left-0">
                <div className="flex justify-between border-b bg-white border-gray-200 items-center w-full lg:p-6 py-3 pl-2 pr-4 lg:shadow-none shadow-xl shadow-gray-200">
                    <button onClick={togglemenu} className="block relative lg:hidden">
                        <svg className="w-9 h-9 rotate-180 text-blacker dark:text-textdark" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.7} d="M4 6h16M4 12h8m-8 6h16" /></svg>
                    </button>
                    {/* <div
                    className="block relative lg:hidden">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fillRule="evenodd" clipRule="evenodd" d="M11.2753 2.71436C16.0029 2.71436 19.8363 6.54674 19.8363 11.2753C19.8363 16.0039 16.0029 19.8363 11.2753 19.8363C6.54674 19.8363 2.71436 16.0039 2.71436 11.2753C2.71436 6.54674 6.54674 2.71436 11.2753 2.71436Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        <path fillRule="evenodd" clipRule="evenodd" d="M19.8987 18.4878C20.6778 18.4878 21.3092 19.1202 21.3092 19.8983C21.3092 20.6783 20.6778 21.3097 19.8987 21.3097C19.1197 21.3097 18.4873 20.6783 18.4873 19.8983C18.4873 19.1202 19.1197 18.4878 19.8987 18.4878Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                </div> */}
                    <div className="lg:flex hidden w-4/6 justify-center items-center space-x-2">
                        <Link href={'/'}>
                            <div className='w-full flex dark:text-textdark sans-bolisher text-2xl text-transparent bg-clip-text bg-gradient-to-t from-indigo-700 to-primary justify-start items-center'>
                                MegaWaat
                            </div>
                        </Link>
                    </div>
                    <div className="hidden  w-[25%] justify-cneter items-center lg:space-x-2">
                        <Link href={'/'}>
                            <img src="/images/logo2.png" />
                        </Link>
                    </div>
                    <div className="lg:flex hidden z-40 justify-center items-center w-full">
                        <div className="border w-full h-12 flex justify-center items-center border-gray-300 rounded-xl">
                            {/* <p className="text-xs flex justify-between items-center 1 w-[13rem] text-gray-700 px-4">
                            همه دسته بندی ها
                            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 9l-7 7-7-7" /></svg>
                        </p> */}
                            <Menu>
                                <Menu.Button className={'focus:outline-none'}>
                                    <div className="text-xs flex justify-between items-center w-[9rem]  text-gray-700 px-4">
                                        {selectcategory ? selectcategory : 'همه دسته بندی ها'}
                                    </div>
                                </Menu.Button>
                                <Transition
                                    as={'div'}
                                    enter="transition ease-out duration-150"
                                    enterFrom="transform opacity-0 scale-75"
                                    enterTo="transform opacity-100 scale-100"
                                    leave="transition ease-in duration-150"
                                    leaveFrom="transform opacity-100 scale-100"
                                    leaveTo="transform opacity-0 scale-75">
                                    <Menu.Items className="absolute z-40 right-0 translate-x-36 border top-8 shadow-xl transition ease-out duration-150 w-48 divide-y divide-gray-200 dark:divide-gray-800 rounded-md bg-white dark:bg-brown ring-1 ring-black ring-opacity-5 focus:outline-none">
                                        <div className="px-1 py-1 ">
                                            <Menu.Item>
                                                {({ active }) => (
                                                    <button
                                                        onClick={() => setselectcategory('همه')}
                                                        className={`transition-all ease-out duration-200 ${active ? 'bg-primary text-white' : 'dark:text-textdark text-blacker'
                                                            } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                                                    >
                                                        {/* <Image src={iranIcon} width={'32px'} height={'32px'} /> */}
                                                        <span className='mx-2 font-thin'>همه</span>
                                                    </button>
                                                )}
                                            </Menu.Item>
                                        </div>
                                        <div className="px-1 py-1 ">
                                            <Menu.Item>
                                                {({ active }) => (
                                                    <button
                                                        onClick={() => setselectcategory('آکادمی مهندسی')}
                                                        className={`transition-all ease-out duration-200 ${active ? 'bg-primary text-white' : 'dark:text-textdark text-blacker'
                                                            } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                                                    >
                                                        {/* <Image src={iranIcon} width={'32px'} height={'32px'} /> */}
                                                        <span className='mx-2 font-thin'>آکادمی مهندسی</span>
                                                    </button>
                                                )}
                                            </Menu.Item>
                                        </div>
                                        <div className="px-1 py-1 ">
                                            <Menu.Item>
                                                {({ active }) => (
                                                    <button
                                                        onClick={() => setselectcategory('مهندسان خبره')}
                                                        className={`transition-all ease-out duration-200 ${active ? 'bg-primary text-white' : 'dark:text-textdark text-blacker'
                                                            } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                                                    >
                                                        {/* <Image src={EnglishIcon} width={'32px'} height={'32px'} /> */}
                                                        <span className='mx-2 font-thin'>مهندسان خبره</span>
                                                    </button>
                                                )}
                                            </Menu.Item>
                                        </div>
                                        <div className="px-1 py-1 ">
                                            <Menu.Item>
                                                {({ active }) => (
                                                    <button
                                                        onClick={() => setselectcategory('کالا و تجهیزات')}
                                                        className={`transition-all ease-out duration-200 ${active ? 'bg-primary text-white' : 'dark:text-textdark text-blacker'
                                                            } group flex w-full items-center rounded-md px-2 py-2 text-sm`}
                                                    >
                                                        {/* <Image src={EnglishIcon} width={'32px'} height={'32px'} /> */}
                                                        <span className='mx-2 font-thin'>کالا و تجهیزات</span>
                                                    </button>
                                                )}
                                            </Menu.Item>
                                        </div>
                                    </Menu.Items>
                                </Transition>
                            </Menu>
                            <div className="relative w-full">
                                <input className="w-full text-sm rounded-l-xl px-4 placeholder:font-black h-12 border-y border-r border-gray-300 outline-none"
                                    type='text'
                                    placeholder="جـستجو بـین بـیش ا ز ۱۰,۰۰۰  آموزش و محصول"
                                />
                                <div className="absolute left-0 top-0 bottom-0 h-full w-14 flex justify-center items-center">
                                    <svg className="w-6 h-6 rotate-90 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="flex justify-end lg:w-4/6 w-auto items-center">
                        <div className="relative flex space-x-5 justify-between items-center">
                            <div></div>
                            <div className="hidden relative">
                                <ThemeToggle />
                            </div>
                            <Menu>
                                <Menu.Button className="relative flex justify-start items-center">
                                    <strong className="mx-1 capitalize sans-bolish text-sm">{lng}</strong>
                                    <svg className="w-6 h-6 text-blacker" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                </Menu.Button>
                                <Transition
                                    as={Fragment}
                                    enter="transition ease-out duration-150"
                                    enterFrom="transform opacity-0 scale-75"
                                    enterTo="transform opacity-100 scale-100"
                                    leave="transition ease-in duration-150"
                                    leaveFrom="transform opacity-100 scale-100"
                                    leaveTo="transform opacity-0 scale-75">
                                    <Menu.Items className="absolute -left-10 lg:left-4 bg-white top-0 transition ease-out duration-150  mt-12 w-60 origin-top-right divide-y divide-gray-200 dark:divide-gray-700 rounded-lg dark:bg-brown shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                                        <div className="px-1 py-1 ">
                                            <Menu.Item>
                                                {({ active }) => (
                                                    <button
                                                        onClick={() => {
                                                            localStorage.setItem('lng', 'fa');
                                                            setlng('fa');
                                                            toast.success('زبان شما به فارسی تغییر کرده است');
                                                            window.location.reload();
                                                        }}
                                                        className={`transition-all ease-out duration-200 ${active ? 'bg-primary text-white' : 'dark:text-textdark text-blacker'
                                                            } group flex w-full items-center rounded-lg px-2 py-2 text-sm`}
                                                    >
                                                        <Image src={iranIcon} width={'32px'} height={'32px'} />
                                                        <span className='mx-4'>فارسی</span>
                                                    </button>
                                                )}
                                            </Menu.Item>
                                        </div>
                                        <div className="px-1 py-1 ">
                                            <Menu.Item>
                                                {({ active }) => (
                                                    <button
                                                        onClick={() => {
                                                            localStorage.setItem('lng', 'en');
                                                            setlng('en');
                                                            toast.success('زبان شما به انگلیسی تغییر کرده است');
                                                            window.location.reload();
                                                        }}
                                                        className={`transition-all ease-out duration-200 ${active ? 'bg-primary text-white' : 'dark:text-textdark text-blacker'
                                                            } group flex w-full items-center rounded-lg px-2 py-2 text-sm`}
                                                    >
                                                        <Image src={EnglishIcon} width={'32px'} height={'32px'} />
                                                        <span className='mx-4'>انگلیسی</span>
                                                    </button>
                                                )}
                                            </Menu.Item>
                                        </div>
                                    </Menu.Items>
                                </Transition>
                            </Menu>
                            <Link href={'/cart'}>
                                <div className="hidden relative lg:block cursor-pointer">
                                    <>
                                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M16.3638 6.86985C16.3638 4.48385 14.4298 2.54985 12.0438 2.54985C9.65783 2.53885 7.71583 4.46485 7.70483 6.85085V6.86985" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M14.9727 11.3738H14.9267" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                            <path d="M9.14165 11.3738H9.09565" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                            <path fillRule="evenodd" clipRule="evenodd" d="M12.0342 21.4894C5.52619 21.4894 4.77719 19.4394 3.31619 14.0224C1.85019 8.58842 4.79119 6.55542 12.0342 6.55542C19.2772 6.55542 22.2182 8.58842 20.7522 14.0224C19.2912 19.4394 18.5422 21.4894 12.0342 21.4894Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                        <div className="absolute -right-1 -bottom-1  flex justify-center p-1 py-[.3px] items-center text-center bg-[#0065FD] rounded-full text-white text-xs">۲</div>
                                    </>
                                </div>
                            </Link>
                        </div>
                        {/* */}
                        {status === 'unauthenticated' ? (
                            <>
                                {localStorage.getItem('tk_mega') === null ? (
                                    <Link href={'/login'}>
                                        <button className='bg-primary py-2 ml-2 px-4 font-thin h-10 rounded-xl text-xs flex justify-center items-center'>
                                            <span className='text-white sans-bolisher mx-2'>ورود <small className="px-0.5 text-textdark">/</small> ثبت نام</span>
                                        </button>
                                    </Link>
                                ) : (
                                    <>
                                        <Popover>
                                            <Popover.Button className="focus:outline-none focus:border-none relative flex justify-start items-center">
                                                {userdata?.userImage && (
                                                    <div className="rounded-full lg:w-10 lg:h-10 w-8 h-8">
                                                        <Image alt="user photo profile" src={'https://megawaat.com/' + userdata?.userImage} className="rounded-full object-cover" width="100%" height="100%" />

                                                    </div>
                                                )}
                                                <div>
                                                    <p className="text-xs flex justify-between items-center sans-bolish text-gray-700 px-2">
                                                        {userdata?.fullName}
                                                        <svg className="w-2 h-2 mr-1" viewBox="0 0 12 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path fillRule="evenodd" clipRule="evenodd" d="M5.89981 9.35387C7.15581 9.35387 11.1708 2.98987 10.4488 2.26787C9.72681 1.54586 2.14181 1.47686 1.35081 2.26787C0.559806 3.05986 4.64481 9.35387 5.89981 9.35387Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                                        </svg>
                                                    </p>
                                                </div>
                                            </Popover.Button>
                                            <Transition
                                                as={Fragment}
                                                enter="transition ease-out duration-150"
                                                enterFrom="transform opacity-0 scale-75"
                                                enterTo="transform opacity-100 scale-100"
                                                leave="transition ease-in duration-150"
                                                leaveFrom="transform opacity-100 scale-100"
                                                leaveTo="transform opacity-0 scale-75">
                                                <Popover.Panel className="absolute lg:left-4 left-0 top-0 transition ease-out duration-150 lg:mt-20 mt-16 w-56 origin-top-right divide-y divide-gray-200 dark:divide-gray-700 rounded-lg bg-white dark:bg-brown shadow ring-1 ring-black ring-opacity-5 focus:outline-none">
                                                    <div className="px-2 pt-0 pb-2">
                                                        {status === 'authenticated' && (
                                                            <div className="flex  pb-3 border-b border-gray-200 w-full">
                                                                <div className="rounded-full w-12 h-12">
                                                                    <Image alt="user photo profile" src={userdata?.image} className="rounded-full object-cover" width="100%" height="100%" />
                                                                </div>
                                                                <div className="flex justify-start items-start flex-col">
                                                                    <p className="text-md sans-bolish flex justify-start mr-2 items-center sans-bolisher text-gray-700">
                                                                        {session?.user?.name}
                                                                    </p>
                                                                    <p className="text-sm flex mr-2 mt-0.5 justify-start items-center sans-bolish text-primary">
                                                                        <div className="sans-bolish text-xs">مشاهده پنل کاربری</div>
                                                                        <svg
                                                                            xmlns="http://www.w3.org/2000/svg"
                                                                            width="16"
                                                                            height="16"
                                                                            fill="none"
                                                                            viewBox="0 0 24 24"
                                                                        >
                                                                            <path
                                                                                stroke="currentColor"
                                                                                strokeLinecap="round"
                                                                                strokeLinejoin="round"
                                                                                strokeWidth="1.5"
                                                                                d="M11.3 11.894h8.95"
                                                                            ></path>
                                                                            <path
                                                                                fillRule="evenodd"
                                                                                stroke="currentColor"
                                                                                strokeLinecap="round"
                                                                                strokeLinejoin="round"
                                                                                strokeWidth="1.5"
                                                                                d="M3.646 11.9c0 1.256 6.364 5.27 7.086 4.549.722-.722.791-8.307 0-9.098-.792-.791-7.086 3.294-7.086 4.549z"
                                                                                clipRule="evenodd"
                                                                            ></path>
                                                                        </svg>
                                                                    </p>
                                                                </div>
                                                            </div>
                                                        )}
                                                        <div className="mt-3 flex justify-start flex-col items-start">
                                                            <div className="flex hover:text-primary text-gray-700 group px-3 py-3 w-full justify-start items-centerw-full rounded-lg transition duration-200 ease hover:bg-primary/10">
                                                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
                                                                <span className={`mr-2 sans-bolish text-sm`}>پروفایل</span>
                                                            </div>
                                                            <div className="flex hover:text-primary text-gray-700 group px-3 py-3 w-full justify-start items-centerw-full rounded-lg transition duration-200 ease hover:bg-primary/10">
                                                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>
                                                                <span className={`mr-2 sans-bolish text-sm`}>پیام ها</span>
                                                            </div>
                                                            <div onClick={logout} className="flex hover:text-primary text-gray-700 group px-3 py-3 w-full justify-start items-centerw-full rounded-lg transition duration-200 ease hover:bg-primary/10">
                                                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
                                                                <span className={`mr-2 sans-bolish text-sm`}>خروج از حساب کاربری</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </Popover.Panel>
                                            </Transition>
                                        </Popover>

                                    </>
                                )}
                            </>
                        ) : (
                            <div className="lg:flex cursor-pointer hidden justify-center items-center border-r pr-3 border-gray-300">
                                {/* Profile Dropdown information */}
                                {status === 'authenticated' && (
                                    <>
                                        <Popover>
                                            <Popover.Button className="focus:outline-none focus:border-none relative flex justify-start items-center">
                                                <div className="rounded-full w-10 h-10">
                                                    <Image alt="user photo profile" src={session?.user?.image} className="rounded-full object-cover" width="100%" height="100%" />
                                                </div>
                                                <div>
                                                    <p className="text-xs flex justify-between items-center sans-bolish text-gray-700 px-2">
                                                        {session?.user?.name}
                                                        <svg className="w-2 h-2 mr-1" viewBox="0 0 12 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path fillRule="evenodd" clipRule="evenodd" d="M5.89981 9.35387C7.15581 9.35387 11.1708 2.98987 10.4488 2.26787C9.72681 1.54586 2.14181 1.47686 1.35081 2.26787C0.559806 3.05986 4.64481 9.35387 5.89981 9.35387Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                                        </svg>
                                                    </p>
                                                </div>
                                            </Popover.Button>
                                            <Transition
                                                as={Fragment}
                                                enter="transition ease-out duration-150"
                                                enterFrom="transform opacity-0 scale-75"
                                                enterTo="transform opacity-100 scale-100"
                                                leave="transition ease-in duration-150"
                                                leaveFrom="transform opacity-100 scale-100"
                                                leaveTo="transform opacity-0 scale-75">
                                                <Popover.Panel className="absolute left-4 top-0 transition ease-out duration-150 lg:mt-20 mt-12 w-64 origin-top-right divide-y divide-gray-200 dark:divide-gray-700 rounded-lg bg-white dark:bg-brown shadow ring-1 ring-black ring-opacity-5 focus:outline-none">
                                                    <div className="p-4">
                                                        {status === 'authenticated' && (
                                                            <div className="flex  pb-3 border-b border-gray-200 w-full">
                                                                <div className="rounded-full w-12 h-12">
                                                                    <Image alt="user photo profile" src={session?.user?.image} className="rounded-full object-cover" width="100%" height="100%" />
                                                                </div>
                                                                <div className="flex justify-start items-start flex-col">
                                                                    <p className="text-md sans-bolish flex justify-start mr-2 items-center sans-bolisher text-gray-700">
                                                                        {session?.user?.name}
                                                                    </p>
                                                                    <p className="text-sm flex mr-2 mt-0.5 justify-start items-center sans-bolish text-primary">
                                                                        <div className="sans-bolish text-xs">مشاهده پنل کاربری</div>
                                                                        <svg
                                                                            xmlns="http://www.w3.org/2000/svg"
                                                                            width="16"
                                                                            height="16"
                                                                            fill="none"
                                                                            viewBox="0 0 24 24"
                                                                        >
                                                                            <path
                                                                                stroke="currentColor"
                                                                                strokeLinecap="round"
                                                                                strokeLinejoin="round"
                                                                                strokeWidth="1.5"
                                                                                d="M11.3 11.894h8.95"
                                                                            ></path>
                                                                            <path
                                                                                fillRule="evenodd"
                                                                                stroke="currentColor"
                                                                                strokeLinecap="round"
                                                                                strokeLinejoin="round"
                                                                                strokeWidth="1.5"
                                                                                d="M3.646 11.9c0 1.256 6.364 5.27 7.086 4.549.722-.722.791-8.307 0-9.098-.792-.791-7.086 3.294-7.086 4.549z"
                                                                                clipRule="evenodd"
                                                                            ></path>
                                                                        </svg>
                                                                    </p>
                                                                </div>
                                                            </div>
                                                        )}
                                                        <div className="mt-3 flex justify-start flex-col items-start">
                                                            <div className="flex hover:text-primary text-gray-700 group px-3 py-3 w-full justify-start items-centerw-full rounded-lg transition duration-200 ease hover:bg-primary/10">
                                                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
                                                                <span className={`mr-2 sans-bolish text-sm`}>پروفایل</span>
                                                            </div>
                                                            <div className="flex hover:text-primary text-gray-700 group px-3 py-3 w-full justify-start items-centerw-full rounded-lg transition duration-200 ease hover:bg-primary/10">
                                                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>
                                                                <span className={`mr-2 sans-bolish text-sm`}>پیام ها</span>
                                                            </div>
                                                            <button onClick={status === 'unauthenticated' ? logout : () => signOut()} className="flex hover:text-primary text-gray-700 group px-3 py-3 w-full justify-start items-centerw-full rounded-lg transition duration-200 ease hover:bg-primary/10">
                                                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
                                                                <span className={`mr-2 sans-bolish text-sm`}>خروج از حساب کاربری</span>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </Popover.Panel>
                                            </Transition>
                                        </Popover>

                                    </>
                                )}
                            </div>
                        )}

                    </div>
                </div>
                {router.pathname === '/' && (
                    <section className="bg-white lg:flex hidden justify-center border-b border-gray-200 items-center w-full py-4">
                        <nav className="flex justify-center items-center w-full">
                            <ul className="w-full space-x-7 flex justify-center items-center relative">
                                <div></div>
                                <NavItem title={'آکادمی مهندسی'} route="/category">
                                    <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path fillRule="evenodd" clipRule="evenodd" d="M21.0003 6.6738C21.0003 8.7024 19.3551 10.3476 17.3265 10.3476C15.2979 10.3476 13.6536 8.7024 13.6536 6.6738C13.6536 4.6452 15.2979 3 17.3265 3C19.3551 3 21.0003 4.6452 21.0003 6.6738Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                        <path fillRule="evenodd" clipRule="evenodd" d="M10.3467 6.6738C10.3467 8.7024 8.7024 10.3476 6.6729 10.3476C4.6452 10.3476 3 8.7024 3 6.6738C3 4.6452 4.6452 3 6.6729 3C8.7024 3 10.3467 4.6452 10.3467 6.6738Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                        <path fillRule="evenodd" clipRule="evenodd" d="M21.0003 17.2619C21.0003 19.2905 19.3551 20.9348 17.3265 20.9348C15.2979 20.9348 13.6536 19.2905 13.6536 17.2619C13.6536 15.2333 15.2979 13.5881 17.3265 13.5881C19.3551 13.5881 21.0003 15.2333 21.0003 17.2619Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                        <path fillRule="evenodd" clipRule="evenodd" d="M10.3467 17.2619C10.3467 19.2905 8.7024 20.9348 6.6729 20.9348C4.6452 20.9348 3 19.2905 3 17.2619C3 15.2333 4.6452 13.5881 6.6729 13.5881C8.7024 13.5881 10.3467 15.2333 10.3467 17.2619Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </NavItem>
                                <NavItem title={'مهندسان خبره'} route="/cofe-dojeldi">
                                    <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M8.54248 9.21777H15.3975" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                        <path fillRule="evenodd" clipRule="evenodd" d="M11.9702 2.5C5.58324 2.5 4.50424 3.432 4.50424 10.929C4.50424 19.322 4.34724 21.5 5.94324 21.5C7.53824 21.5 10.1432 17.816 11.9702 17.816C13.7972 17.816 16.4022 21.5 17.9972 21.5C19.5932 21.5 19.4362 19.322 19.4362 10.929C19.4362 3.432 18.3572 2.5 11.9702 2.5Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </NavItem>
                                <NavItem title={'کالا و تجهیزات'} route="/cofe-dojeldi">
                                    <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path fillRule="evenodd" clipRule="evenodd" d="M2.75 12C2.75 18.937 5.063 21.25 12 21.25C18.937 21.25 21.25 18.937 21.25 12C21.25 5.063 18.937 2.75 12 2.75C5.063 2.75 2.75 5.063 2.75 12Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                        <path fillRule="evenodd" clipRule="evenodd" d="M8.69775 15.3022L10.2718 10.2722L15.3018 8.69824L13.7278 13.7272L8.69775 15.3022Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </NavItem>
                                <div className="relative">
                                    <Popover>
                                        <Popover.Button className={`text-gray-700 hover:text-gray-900 transition duration-150 text-xs font-medium flex justify-center items-center focus:outline-none focus:border-none`}>
                                            <span>
                                                <svg className="w-4 h-4 text-[#0065FD]" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M12.0368 8.46265V15.6111" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                                    <path d="M15.6148 12.0368H8.45898" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                                    <path fillRule="evenodd" clipRule="evenodd" d="M2.30005 12.0369C2.30005 4.73479 4.73479 2.30005 12.0369 2.30005C19.339 2.30005 21.7737 4.73479 21.7737 12.0369C21.7737 19.339 19.339 21.7737 12.0369 21.7737C4.73479 21.7737 2.30005 19.339 2.30005 12.0369Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                                </svg>
                                            </span>
                                            <span className="mr-1 sans-bolish text-primary">ایجاد و بارگذاری</span>
                                        </Popover.Button>
                                        <Subdrop title={'آکادمی مهندسی'} data={
                                            {
                                                'آکادمی مهندسی': [
                                                    'آکادمی مهندسی',
                                                    'بارگذاری کالا و تجهیزات',
                                                    'مهندسان خبره'
                                                ],
                                                'مهندسان خبره': [
                                                    'آکادمی مهندسی',
                                                    'بارگذاری کالا و تجهیزات',
                                                    'مهندسان خبره'
                                                ],
                                                'کالا و تجهیزات': [
                                                    'آکادمی مهندسی',
                                                    'بارگذاری کالا و تجهیزات',
                                                    'مهندسان خبره'
                                                ],

                                            }
                                        } />
                                    </Popover>
                                </div>

                            </ul>
                        </nav>
                    </section>
                )}
            </div>
            <div className="pb-20">
                {children}
            </div>
            <div className="lg:hidden z-50 flex fixed bottom-0 left-0 right-0 justify-center border-t border-gray-100 bg-white items-center w-full lg:p-6 py-4">
                <div className="flex justify-between items-center space-x-2 w-full">
                    <div className="text-gray-600 w-full flex flex-col items-center justify-center space-y-2">
                        <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9.07861 16.1355H14.8936" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M2.3999 13.713C2.3999 8.082 3.0139 8.475 6.3189 5.41C7.7649 4.246 10.0149 2 11.9579 2C13.8999 2 16.1949 4.235 17.6539 5.41C20.9589 8.475 21.5719 8.082 21.5719 13.713C21.5719 22 19.6129 22 11.9859 22C4.3589 22 2.3999 22 2.3999 13.713Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                        <span className="text-xs sans-bolish">آکادمی</span>
                    </div>
                    <div className="text-gray-600 w-full flex flex-col items-center justify-center space-y-2">
                        <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fillRule="evenodd" clipRule="evenodd" d="M21.0003 6.6738C21.0003 8.7024 19.3551 10.3476 17.3265 10.3476C15.2979 10.3476 13.6536 8.7024 13.6536 6.6738C13.6536 4.6452 15.2979 3 17.3265 3C19.3551 3 21.0003 4.6452 21.0003 6.6738Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M10.3467 6.6738C10.3467 8.7024 8.7024 10.3476 6.6729 10.3476C4.6452 10.3476 3 8.7024 3 6.6738C3 4.6452 4.6452 3 6.6729 3C8.7024 3 10.3467 4.6452 10.3467 6.6738Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M21.0003 17.2619C21.0003 19.2905 19.3551 20.9348 17.3265 20.9348C15.2979 20.9348 13.6536 19.2905 13.6536 17.2619C13.6536 15.2333 15.2979 13.5881 17.3265 13.5881C19.3551 13.5881 21.0003 15.2333 21.0003 17.2619Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M10.3467 17.2619C10.3467 19.2905 8.7024 20.9348 6.6729 20.9348C4.6452 20.9348 3 19.2905 3 17.2619C3 15.2333 4.6452 13.5881 6.6729 13.5881C8.7024 13.5881 10.3467 15.2333 10.3467 17.2619Z" stroke="CurrentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>

                        <span className="text-xs sans-bolish">مهندسان خبره</span>
                    </div>
                    <div className="text-gray-600 w-full flex flex-col items-center justify-center space-y-2">
                        <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fillRule="evenodd" clipRule="evenodd" d="M11.8445 21.6618C8.15273 21.6618 5 21.0873 5 18.7865C5 16.4858 8.13273 14.3618 11.8445 14.3618C15.5364 14.3618 18.6891 16.4652 18.6891 18.766C18.6891 21.0658 15.5564 21.6618 11.8445 21.6618Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                            <path fillRule="evenodd" clipRule="evenodd" d="M11.8372 11.1735C14.26 11.1735 16.2236 9.2099 16.2236 6.78718C16.2236 4.36445 14.26 2.3999 11.8372 2.3999C9.41452 2.3999 7.44998 4.36445 7.44998 6.78718C7.4418 9.20172 9.3918 11.1654 11.8063 11.1735C11.8172 11.1735 11.8272 11.1735 11.8372 11.1735Z" stroke="CurrentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>

                        <span className="text-xs sans-bolish">کالا تجهیزات</span>
                    </div>
                </div>
            </div>
            <motion.div
                initial={{ x: [-1000, 100] }}
                animate={{ x: menu }}
                transition={
                    {
                        duration: .4,
                        type: 'spring'
                    }
                }
                className="z-50 fixed lg:hidden block inset-0 backdrop-blur-[10px] w-full h-full"
            >
                <motion.div className="w-[75%] relative overflow-hidden dark:bg-brown bg-white h-full ">
                    <div className="px-6 py-3 w-full">
                        <div className='flex justify-between items-center w-full'>
                            <button onClick={togglemenu} className="z-50">
                                <svg
                                    className="z-50 let-10 top-4 w-10 h-10 p-2 bg-primary dark:text-textdark rounded-xl"
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={1.5}
                                        d="M6 18L18 6M6 6l12 12"
                                    />
                                </svg>
                            </button>
                            <Link href={'/login'}>
                                <button className='bg-primary py-2 px-4 font-thin h-10 rounded-xl text-sm flex justify-center items-center'>
                                    <span className='text-white font-normal mx-2'>ورود / ثبت نام</span>
                                </button>
                            </Link>
                        </div>
                        {/* Shape  */}
                        <div className="p-20 z-10 absolute -top-16 -right-16 rounded-full bg-primary/20 flex justify-start items-start blur-3xl"></div>
                        {/* Shape  */}

                        <div className='mt-12'>
                            <div className='w-full pb-6 text-gray-800 flex dark:text-textdark sans-bolisher text-2xl justify-center items-center'>
                                MegaWaat
                            </div>
                            {/* <hr /> */}
                            <div className='w-full mx-auto h-[1px] bg-gray-200 dark:bg-gray-600'></div>
                            <ul className="flex justify-center mt-6 flex-col capitalize items-center w-full text-2xl space-y-2 text-white">
                                <div className='p-2 rounded-[25px] w-full flex justify-start items-center'>
                                    <div>
                                        <div className='w-10 h-10 bg-gray-200 text-blacker dark:text-wither dark:bg-primary2 flex justify-center rounded-full items-center'>
                                            <ThemeToggle />
                                        </div>
                                    </div>
                                    <div className='text-sm mx-4 text-blacker dark:text-textdark sans-bolish'>
                                        تم تاریک
                                    </div>
                                </div>
                                <div className='p-2 rounded-[25px] w-full flex justify-start items-center'>
                                    <Link href="/">
                                        <>
                                            <div>
                                                <div className='w-10 h-10 bg-gray-200 text-blacker dark:text-wither dark:bg-primary2 flex justify-center rounded-full items-center'>
                                                    <svg
                                                        xmlns="http://www.w3.org/2000/svg"
                                                        width="22"
                                                        height="22"
                                                        className="dark:text-primary dark:group-hover:text-primary group-hover:text-primary"
                                                        fill="none"
                                                        viewBox="0 0 22 22">
                                                        <path
                                                            fillRule="evenodd"
                                                            d="M19.17 14.955l-.704-5.678c-.43-2.027-1.645-2.86-2.803-2.86H6.354c-1.175 0-2.43.775-2.795 2.86l-.713 5.678c-.583 4.17 1.564 5.212 4.367 5.212h7.599c2.795 0 4.877-1.51 4.359-5.212zM8.34 11.136a.822.822 0 01-.81-.834c0-.46.363-.833.81-.833.447 0 .81.373.81.833 0 .46-.363.834-.81.834zm4.496-.834c0 .46.363.834.81.834.448 0 .81-.373.81-.834a.822.822 0 00-.81-.833.822.822 0 00-.81.833z"
                                                            className="fill-current text-biscay-700 dark:text-gray-200 group-hover:text-biscay-300"
                                                            clipRule="evenodd"
                                                        ></path>
                                                        <path
                                                            d="M15.56 6.21a.46.46 0 01-.04.207h-1.318a.595.595 0 01-.04-.207 3.188 3.188 0 00-3.193-3.183A3.188 3.188 0 007.775 6.21a.594.594 0 010 .207h-1.35a.595.595 0 010-.207 4.576 4.576 0 014.58-4.377 4.576 4.576 0 014.578 4.377h-.024z"
                                                            className="fill-current text-biscay-700 dark:text-gray-200 group-hover:text-biscay-300"
                                                            opacity="0.4"
                                                        ></path>
                                                    </svg>
                                                </div>
                                            </div>
                                            <div className='text-sm mx-4 text-blacker dark:text-textdark sans-bolish'>
                                                سبد خرید
                                            </div>
                                        </>
                                    </Link>
                                </div>
                                <div className='p-2 rounded-[25px] w-full flex justify-start items-center'>
                                    <Link href="/">
                                        <>
                                            <div>
                                                <div className='w-10 h-10 bg-gray-200 text-blacker dark:text-wither dark:bg-primary2 flex justify-center rounded-full items-center'>
                                                    <svg
                                                        xmlns="http://www.w3.org/2000/svg"
                                                        width="14"
                                                        height="17"
                                                        fill="none"
                                                        className="dark:text-primary dark:group-hover:text-primary group-hover:text-primary"
                                                        viewBox="0 0 14 17"
                                                    >
                                                        <path
                                                            d="M13.301 8.503c-.592-.692-.861-1.292-.861-2.31v-.347c0-1.327-.306-2.182-.97-3.037C10.446 1.48 8.723.679 7.036.679h-.072c-1.652 0-3.32.765-4.362 2.039-.7.872-1.042 1.764-1.042 3.128v.347C1.56 7.21 1.31 7.81.7 8.503c-.45.51-.593 1.165-.593 1.874 0 .71.233 1.382.7 1.928a3.676 3.676 0 002.353 1.146c1.274.146 2.548.2 3.841.2 1.293 0 2.567-.091 3.842-.2a3.676 3.676 0 002.351-1.146c.467-.546.7-1.219.7-1.928 0-.71-.143-1.365-.592-1.874"
                                                            className="text-blacker dark:text-wither fill-current"
                                                        ></path>
                                                        <path
                                                            d="M8.63 14.653c-.406-.087-2.877-.087-3.282 0-.347.08-.722.266-.722.675.02.39.248.733.564.951v.001a2.95 2.95 0 001.39.594c.268.037.54.035.817 0a2.95 2.95 0 001.39-.594c.315-.219.543-.563.564-.952 0-.409-.375-.595-.722-.675"
                                                            className="text-blacker dark:text-wither fill-current"
                                                            opacity="0.4"
                                                        ></path>
                                                    </svg>
                                                </div>
                                            </div>
                                            <div className='text-sm mx-4 text-blacker dark:text-textdark sans-bolish'>
                                                اعلانات
                                            </div>
                                        </>
                                    </Link>
                                </div>
                                {/* <hr /> */}
                                <div className='w-full border-t py-2 translate-y-2 border-gray-200 dark:border-gray-600'></div>
                                <div className='p-2 rounded-[25px] w-full mr-5 flex justify-start items-center'>
                                    <button onClick={() => togglenav('/')} className='flex justify-center items-center'>

                                        <div>
                                            <div className=' text-gray-600 dark:text-wither flex justify-center rounded-full items-center'>
                                                <svg
                                                    xmlns="http://www.w3.org/2000/svg"
                                                    width="24.028"
                                                    className=""
                                                    height="23.829"
                                                    viewBox="0 0 24.028 23.829"
                                                >
                                                    <path
                                                        fill="none"
                                                        stroke="currentColor"
                                                        strokeLinecap="round"
                                                        strokeLinejoin="round"
                                                        strokeWidth="2"
                                                        d="M7.04 22.821l10 .007-11-.123a5.863 5.863 0 01-3.018-1.049 3.894 3.894 0 01-1.272-2.348 30.521 30.521 0 01-.513-10 1.838 1.838 0 01.128-.181 8.216 8.216 0 01.675-.736c.6-.6 1.445-1.33 2.4-2.124 1.923-1.576 4.244-3.344 5.937-4.604a2.869 2.869 0 013.427-.008c1.706 1.259 4.048 3.025 5.967 4.61.962.795 1.8 1.529 2.394 2.123a7.282 7.282 0 01.653.725c.048.064.079.111.1.144a38.532 38.532 0 01-.5 10.072 3.707 3.707 0 01-1.244 2.334 5.939 5.939 0 01-3.039 1.042q-.547.068-1.089.125v-6.625a3.147 3.147 0 00-3-3H10.04a3.147 3.147 0 00-3 3v6.575l-1.3-.111zM1.22 9.344v-.006zm21.72-.042v-.007z"
                                                    ></path>
                                                </svg>
                                            </div>
                                        </div>
                                        <Link href={'/'}>
                                            <p className='text-sm mx-4 mt-1 text-blacker dark:text-textdark font-normal'>مگاوات</p>
                                        </Link>

                                    </button>
                                </div>
                            </ul>
                        </div>
                    </div>
                </motion.div>
            </motion.div>
            {/* Footer Home Hero */}
            <div className='lg:block hidden bottom-0 left-0 right-0 w-full'>
                <footer className="flex justify-between items-center h-16 w-full p-4 bg-white dark:bg-brown text-gray-800">
                    <div></div>
                    <div className='relative w-40 h-40 mx-auto flex justify-center items-center'>
                        <Link href={'/'}><Image src={logo} className='h-full w-full' /></Link>
                    </div>
                    <div></div>
                </footer>
            </div>
        </div>
    )
}
